version: '3.8'
services:
  #Nginx Service
  webserver:
    image: ${APP_IMAGE_NAME}:4.4.1
    container_name: ampache_nginx
    build: ampache_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - music:/ampache/music

  #MySQL Service
  db:
    image: ${DB_IMAGE_NAME}:dev
    container_name: ampache_db
    build: ampache_db
    restart: unless-stopped
    tty: true
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      DB: ${AMPACHE_DB}ampache
      USER: ${AMPACHE_DB_USER}ampache
      PASSWORD: ${AMPACHE_DB_PASSWORD}12test34

volumes:
  db_data: {}
  music: {}

#Docker Networks
networks:
  app-network:
    driver: bridge

# You will need to change this
# Keep in mind docker compose is simplistic and cannot deploy
#  in a VPC which has more than 1 subnet per AZ (it doesn't know which is the public subnet)
#  https://github.com/docker/compose-cli/issues/1411
x-aws-vpc: vpc-fe68e599
